from turtle import Turtle, Screen

timmy = Turtle()
my_screen = Screen()
timmy.shape("turtle")
timmy.color("green")
timmy.fd(100)
timmy.lt(90)
timmy.fd(100)
timmy.rt(90)
timmy.bk(100)
timmy.rt(90)
timmy.fd(100)
print(my_screen.canvheight)
print(timmy)
my_screen.exitonclick()